name: Reusable Build

on:
  workflow_call:
    inputs:
      artifact_version:
        required: true
        type: string

env:
  UV_PYTHON: 3.12
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1

jobs:
  build:
    name: Build linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install Linux dependencies
        shell: bash
        run: |
            sudo apt update --allow-releaseinfo-change
            sudo apt-get install -y \
              clang ninja-build libgtk-3-dev libasound2-dev cmake llvm-18 lld libmpv-dev mpv

            sudo apt-get clean

      - name: Build app
        shell: bash
        run: |
          uv sync
          uv run flet build linux --product Redwood --build-version ${{ inputs.artifact_version }} --yes 
          mv build/linux/redwood build/linux/redwood-${{ inputs.artifact_version }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: artifact
          path: build/linux/redwood-${{ inputs.artifact_version }}
          if-no-files-found: error
          overwrite: false
          retention-days: 7
