# .github/workflows/release.yaml
name: Production Release

on:
  push:
    tags:
      - 'v*'

jobs:
  call-build:
    uses: ./.github/workflows/_build.yaml
    with:
      artifact_version: ${{ github.ref_name }}

  create-release:
    needs: call-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets
          pattern: redwood-*
          merge-multiple: false

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-assets/redwood-*
          draft: false
          prerelease: false
